# Generated by Django 3.1.5 on 2021-01-29 20:28

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(first_name="Bruno", last_name="José", email="brunojndias@gmail.com", phone="88996351705", address="Rua Delta", description= "Minha descrição").save()

class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_data),
    ]